import { getRatingClass } from "./helper.js";

export const userState = {
  user: {
    displayName: "",
    avatar: "",
  },
  selectedFilter: "football",

  cards: {
    basketball: [
      {
        id: "092",
        playerName: "Shai Gilgeous-Alexander",
        sport: "basketball",
        team: "Oklahoma City Thunder",
        age: 27,
        rating: 98,
        rarity: 30,
        value: 4500,
        impact: 40,
        image: "assets/images/shai-gilgeous-alexander.png",
      },

      {
        id: "011",
        playerName: "Nikola Jokić",
        sport: "basketball",
        team: "Denver Nuggets",
        age: 31,
        rating: 98,
        rarity: 32,
        value: 2310,
        impact: 40,
        image: "assets/images/nikola-jokic.png",
      },

      {
        id: "281",
        playerName: "Anthony Edwards",
        sport: "basketball",
        team: "Minnesota Timberwolves",
        age: 24,
        rating: 96,
        rarity: 25,
        value: 1500,
        impact: 30,
        image: "assets/images/anthony-edwards.png",
      },

      {
        id: "307",
        playerName: "Scottie Barnes",
        sport: "basketball",
        team: "Toronto Raptors",
        age: 24,
        rating: 89,
        rarity: 20,
        value: 700,
        impact: 25,
        image: "assets/images/scottie-barnes.png",
      },

      {
        id: "218",
        playerName: "Dylan Harper",
        sport: "basketball",
        team: "San Antonio Spurs",
        age: 20,
        rating: 79,
        rarity: 20,
        value: 564,
        impact: 15,
        image: "assets/images/dylan-harper.png",
      },

      {
        id: "2810",
        playerName: "Ajay Mitchell",
        sport: "basketball",
        team: "Oklahoma City Thunder",
        age: 24,
        rating: 75,
        rarity: 10,
        value: 320,
        impact: 15,
        image: "assets/images/ajay-mitchell.png",
      },

      {
        id: "90032",
        playerName: "Bez Mbeng",
        sport: "basketball",
        team: "Utah Jazz",
        age: 23,
        rating: 65,
        rarity: 1,
        value: 50,
        impact: 2,
        image: "assets/images/default-card.png",
      },
    ],
    football: [
      {
        id: "543",
        playerName: "Ousmane Dembélé",
        sport: "football",
        team: "Paris Saint-Germain",
        age: 28,
        rating: 94,
        rarity: 30,
        value: 5200,
        impact: 30,
        image: "assets/images/ous-dembele.png",
      },
      {
        id: "342",
        playerName: "Myles Lewis-Skelly",
        sport: "football",
        team: "Arsenal",
        age: 19,
        rating: 73,
        rarity: 10,
        value: 600,
        impact: 8,
        image: "assets/images/lewis-skelly.png",
      },
      {
        id: "777",
        playerName: "Bukayo Saka",
        sport: "football",
        team: "Arsenal",
        age: 24,
        rating: 89,
        rarity: 25,
        value: 1200,
        impact: 20,
        image: "assets/images/bukayo-saka.png",
      },
      {
        id: "532",
        playerName: "Lamine Yamal",
        sport: "football",
        team: "Barcelona",
        age: 18,
        rating: 88,
        rarity: 25,
        value: 3100,
        impact: 26,
        image: "assets/images/lamine-yamal.png",
      },

      {
        id: "213",
        playerName: "Désiré Doué",
        sport: "football",
        team: "Paris Saint Germain",
        age: 20,
        rating: 80,
        rarity: 25,
        value: 2100,
        impact: 20,
        image: "assets/images/desire-doue.png",
      },
      {
        id: "125",
        playerName: "Kobbie Mainoo",
        sport: "football",
        team: "Manchester United",
        age: 20,
        rating: 74,
        rarity: 20,
        value: 1000,
        impact: 20,
        image: "assets/images/kobbie-mainoo.png",
      },
      {
        id: "41",
        playerName: "Declan Rice",
        sport: "football",
        team: "Arsenal",
        age: 26,
        rating: 91,
        rarity: 35,
        value: 1600,
        impact: 20,
        image: "assets/images/declan-rice.png",
      },

      {
        id: "98",
        playerName: "Kylian Mbappe",
        sport: "football",
        team: "Real Madrid",
        age: 26,
        rating: 98,
        rarity: 40,
        value: 4500,
        impact: 45,
        image: "assets/images/kylian-mbappe.png",
      },

      {
        id: "4198",
        playerName: "Max Dowman",
        sport: "football",
        team: "Arsenal",
        age: 16,
        rating: 64,
        rarity: 15,
        value: 1500,
        impact: 15,
        image: "assets/images/default-card.png",
      },
    ],
  },
  bag: [],
  activeOrders: [],
  pastOrders: [],

  settings: "light",
};
